services:
  ws:
    ecsServiceName: xxxxxx-ws-service
    displayName: WebSocket Service
    scalable: true
    minCount: 0
    maxCount: 3
    loadBalancerType: alb
    targetConnectionsPerTask: 30

  ds:
    ecsServiceName: xxxxxx-ds-service
    displayName: Dispatcher Service
    scalable: false
    minCount: 0
    maxCount: 1
    loadBalancerType: nlb

  ns:
    ecsServiceName: xxxxxx-ns-service
    displayName: Notificator Service
    scalable: false
    minCount: 0
    maxCount: 1
    loadBalancerType: alb